name: MultiProtocol
api: 4.0.0
version: 1.3
main: multiprotocol\MultiProtocol
description: Allows players with different versions to join.
website: https://github.com/IceCruelStuff/MultiProtocol
load: STARTUP
